name: peterparker
favicon: null
layout_spectrum: 0.25422
typography_spectrum: 0.7461290413048118
title: peterparker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101318'
    - '#9f0b01'
    - '#000000'
    - '#ffffff'
    - '#ebcdcb'
  brandStrength: 0.13823081692680717
  lightness: 0.07332622352987528
  saturation: 0.7871639851946384
  rhythmicContrast: 0.7065259818919003
purpose: []
